### PR TITLE
refactor: improve folder structure

### PR DESCRIPTION
**Pull request by azat-io**
### Description

Updated the project file structure.

### Additional context

#417.

---

### What is the purpose of this pull request? 

- [ ] Bug fix
- [ ] New Feature
- [ ] Documentation update
- [x] Other

### Before submitting the PR, please make sure you do the following

- [x] Check that there isn't already a PR that solves the problem the same way to avoid creating a duplicate.
- [x] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [x] Ideally, include relevant tests that fail without this PR but pass with it.
- [x] Read [contribution guidelines](https://github.com/azat-io/eslint-plugin-perfectionist/blob/main/contributing.md).

### CODE REVIEW

**Comment by azat-io** [comment]
Everything is currently working correctly except for one test in:
`test/rules/sort-imports/read-closest-ts-config-by-path.test.ts`

**Comment by azat-io** [comment]
Branch tree:
https://github.com/azat-io/eslint-plugin-perfectionist/tree/refactor/structure

**Comment by hugop95** [comment]
@azat-io Fix for the test can be found here: https://github.com/azat-io/eslint-plugin-perfectionist/pull/426.

**Comment by azat-io** [comment]
@hugop95 Nice, thank you!

Ready for review.

**Review by hugop95 — APPROVED** [review]
@azat-io 👍 All good!

[suggestion] What do you think about creating an `index.ts` file in the `utils` folder?

**Comment by azat-io** [comment]
@hugop95 I don't have a clear opinion on this. There are no `index.ts` files in the utilities folders for rules (`rules/sort-array-includes`), it seems logical to me that there is no `index.ts` in `utils`.

**Comment by hugop95** [comment]
@azat-io There is one in `types`, this is why I was asking 🙂. No big difference for me.

**Comment by azat-io** [comment]
Or we could remove `index.ts` from `types/`

**Comment by hugop95** [comment]
@azat-io 

> Or we could remove index.ts from types/

Fine by me as well 👍

**Comment by azat-io** [comment]
Done!

**Pull request merged**
