### PR TITLE
docs: add searchbar

### LINKED ISSUE #224: Docs: Website search
### Describe the rule

https://perfectionist.dev is beautiful ❤️ - but doesn't have a search bar. I was trying to search for some options (#223) and that would have been handy. Would you be open to having one added?

Docs references for common site frameworks:

* https://starlight.astro.build/guides/site-search
* https://docusaurus.io/docs/search

### Code example

n/a

### Additional comments

Sorry for using the wrong template 😅 there wasn't one I could find for docs / website stuff.

### Validations

- [X] Read the [docs](https://perfectionist.dev).
- [X] Check that there isn't [already an issue](https://github.com/azat-io/eslint-plugin-perfectionist/issues) that reports the same bug to avoid creating a duplicate.

### PR DESCRIPTION
**Pull request by yujonglee**
### Description

Resolves #224.

It use [Pagefind](https://pagefind.app/) to create local search index at build-time, and use [Canary](https://getcanary.dev/docs/local/playground) to build SearchBar UI.

https://github.com/user-attachments/assets/f31c8bcf-c2f7-4ae6-b9f6-6f41f1aebac0

### Additional context

---

### What is the purpose of this pull request? 

- [ ] Bug fix
- [ ] New Feature
- [x] Documentation update
- [ ] Other

### Before submitting the PR, please make sure you do the following

- [x] Check that there isn't already a PR that solves the problem the same way to avoid creating a duplicate.
- [x] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [x] Ideally, include relevant tests that fail without this PR but pass with it.
- [x] Read [contribution guidelines](https://github.com/azat-io/eslint-plugin-perfectionist/blob/main/contributing.md).

### CODE REVIEW

**Comment by azat-io** [comment]
Wow. It looks nice. Let's fix linter errors and I'll see it.

**Comment by yujonglee** [comment]
@azat-io  I guess this is ready for review. not sure why CI is not triggered.

**Comment by azat-io** [comment]
Could you resolve merge conflicts?

**Comment by yujonglee** [comment]
@azat-io just did!

**Comment by yujonglee** [comment]
@azat-io  anything I could do to help get this merged in?

**Comment by azat-io** [comment]
Screen Recording 2024-09-08 at 12 42 46 PM

@yujonglee Hello! I tried to start your branch locally. And it seems that the search not working for me.
I'm also a bit confused by the design. I'd like to customize it a bit. Take the search icon from the common icon library. And stylize the search input a bit.

**Comment by yujonglee** [comment]
@azat-io Thank you for trying it out.

I guess you ran `pnpm run docs:dev`. But `astro-pagefind` only generate index in production build. That's why it can not find index and search not work for you.
```
[404] /pagefind/pagefind.js 3ms
```

If you run `pnpm run docs:build` at least once, it will create index, and search will work ``pnpm run docs:dev`. Sorry that I didn't mentioned it earlier.

```
[pagefind] Pagefind indexed 31 pages
[pagefind] Pagefind wrote index to eslint-plugin-perfectionist/dist/pagefind
```

---

Regarding styling & customization, it is very important goal for me to make these components easy to customize. So I would love to hear more about which part of design was confusing for you.

We have docs about the styling here:

https://getcanary.dev/docs/common/customization/styling

For things you mentioned - 

> And stylize the search input a bit.

https://github.com/fastrepl/canary/blob/590fc07d4a2a20d3193d6f7e57c3d28976b9dde1/js/packages/web/src/components/canary-search-input.ts#L39

```css
  canary-search-input::part(input) {
    background-color: red;
  }
```

> Take the search icon from the common icon library. 

https://github.com/fastrepl/canary/blob/590fc07d4a2a20d3193d6f7e57c3d28976b9dde1/js/packages/web/src/components/canary-search.ts#L36-L38

```html
 ...
 <canary-search-input slot="input">
   // plug your icon component and override the default
  <common-icon-lib slot="input-before"></common-icon-lib >
</canary-search-input>
...
```

Any customization should be doable, if Canary expose them with [`slot`](https://developer.mozilla.org/ko/docs/Web/HTML/Element/slot) and [`part`](https://developer.mozilla.org/ko/docs/Web/CSS/::part). Would appreciate if there's anything missing for your use-case.

Thank you.

**Pull request closed without merging**
