### PR TITLE
feat: support for ordering protected properties and methods in classes

### PR DESCRIPTION
**Pull request by williamkolean**
### Description

Adds support for ordering protected properties and methods in a class.

---

### What is the purpose of this pull request? 

- [ ] Bug fix
- [X] New Feature
- [ ] Documentation update
- [ ] Other

### Before submitting the PR, please make sure you do the following

- [X] Check that there isn't already a PR that solves the problem the same way to avoid creating a duplicate.
- [X] Provide a description in this PR that addresses **what** the PR is solving, or reference the issue that it solves (e.g. `fixes #123`).
- [X] Ideally, include relevant tests that fail without this PR but pass with it.
- [X] Read [contribution guidelines](https://github.com/azat-io/eslint-plugin-perfectionist/blob/main/contributing.md).

### CODE REVIEW

**Comment by azat-io** [comment]
Hi, thank you for your pull request. It looks good.

Could you please make the test coverage 100%?

**Comment by williamkolean** [comment]
Sorry for the oversight! Test added, coverage now at 100%.

**Comment by azat-io** [comment]
Awesome, thanks! I'll create a release soon.

**Comment by azat-io** [comment]
Released in [v3.1.0](https://github.com/azat-io/eslint-plugin-perfectionist/releases/tag/v3.1.0).

**Pull request merged**
